In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9])
train_len = 6
print(a[:train_len])
print(a[train_len:])
print(a[:-train_len])
print(a[-train_len:])

[1 2 3 4 5 6]
[7 8 9]
[1 2 3]
[4 5 6 7 8 9]


In [3]:
# where is 1?
a[3:0:-1]

array([4, 3, 2])

In [11]:
# 3 items from the end and do not include the last one
num=3
num = len(a) - 1
a[-2:-num-2:-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [10]:
b = np.array([1,0,0,0,0,1,1,0,1,0,0,1,1,1])
np.argwhere(b==1).flatten()[:10]

array([ 0,  5,  6,  8, 11, 12, 13])